networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true
  internal:

services:
  app:
    image: $CICD_IMAGE_ID
    environment:
      - RMQ_HOST=bus
    networks:
      - bus
      - internal
      # - ingress
    deploy:
      replicas: 1
      # labels:
      #   - 'traefik.enable=true'
      #   - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`${CI_PROJECT_NAME}.${TLD}`)"
      #   - "traefik.http.services.${CICD_STACK_NAME}App.loadbalancer.server.port=8080"
      #   - 'traefik.http.routers.${CICD_STACK_NAME}App.entrypoints=websecure'
      #   - 'traefik.http.routers.${CICD_STACK_NAME}App.tls.certresolver=letsencrypt'
  mongodb:
    image: cr.gitlab.switch.ch/hslu/shared/devops/docker-cache/bitnami/mongodb:4.2.19
    restart: always
    ports:
      - '27018:27017'
    networks:
      - internal
