include:
  - /sys/config/filters.yml
  - /sys/config/stages.yml
  - /sys/config/environments/sys.dev.yml
  - /sys/config/environments/sys.prod.yml

# env switch
workflow:
  rules:
    # env switch by explicit config
    - if: $CICD_TARGET_ENV == 'dev'
      variables:
        CICD_TARGET_DEV: 1
    - if: $CICD_TARGET_ENV == 'prod'
      variables:
        CICD_TARGET_PROD: 1
    - if: $CICD_TARGET_ENV == 'all'
      variables:
        CICD_TARGET_DEV: 2
        CICD_TARGET_PROD: 1

    # env switch by branch name
    - if: $CI_COMMIT_BRANCH == 'prod'
      variables:
        CICD_TARGET_PROD: 1
    - if: $CI_COMMIT_BRANCH == 'main'
      variables:
        CICD_TARGET_PROD: 1

    # default: DEV
    - variables:
        CICD_TARGET_DEV: 2

# job templates with environment config
.job:
  extends: .envConfigSysDev
  tags:
    - $CICD_RUNNER
.jobDev:
  extends: .envConfigSysDev
  tags:
    - $CICD_RUNNER
.jobProd:
  extends: .envConfigSysProd
  tags:
    - $CICD_RUNNER

variables:

  # branch definition
  CICD_BRANCH_PROD: prod
  CICD_BRANCH_SYS: sys

  # resource limits
  CICD_DEFAULT_MAX_MEM: 256Mi
  CICD_DEFAULT_MAX_CPU: 100m
  CICD_DEFAULT_REQ_MEM: 16Mi
  CICD_DEFAULT_REQ_CPU: 10m