########
# BUILD
########
.filterBuild:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    # auto run
    - when: on_success

##########
# PUBLISH
##########
.filterPublish:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    # only on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success

##########
# DEPLOY
##########

.filterDeployment:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    # don't run for MRs
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never

.filterDeploymentDev:
  rules:

    - !reference [.filterDeployment, rules]

    - if: $CICD_TARGET_DEV == '1'
      when: on_success
    - if: $CICD_TARGET_DEV == '2'
      when: manual

.filterDeploymentProd:
  rules:

    - !reference [.filterDeployment, rules]
    - if: $CICD_TARGET_PROD == '1'
      when: on_success
    - if: $CICD_TARGET_PROD == '2'
      when: manual

####################
# DEPLOY add-ons
####################

.filterAdditionalDeployment:
  rules:

    - !reference [.filterDeployment, rules]

    # offer additional deployment(s) for PROD branch
    - if: $CI_COMMIT_BRANCH == 'prod'
      when: manual

.filterDryDeployment:
  rules:

    - !reference [.filterDeployment, rules]

    # only for dev (feature branches, etc.)
    - if: $CICD_TARGET_DEV
      when: on_success