 #
 # Copyright 2024 Hochschule Luzern Informatik.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #      http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
FROM eclipse-temurin:21-jre
RUN useradd --uid 1001 --no-create-home --shell /usr/sbin/nologin worker
USER worker
EXPOSE 8090/tcp
WORKDIR /app
CMD ["/opt/java/openjdk/bin/java", "-jar", "service.jar"]
COPY target/service.jar service.jar
