networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true

services:

  app:
    image: $CICD_IMAGE_ID
    environment:
      - RMQ_HOST=bus
    networks:
      - bus
      - ingress
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`gw-template.${TLD}`)"
        - "traefik.http.services.${CICD_STACK_NAME}App.loadbalancer.server.port=8090"
        - 'traefik.http.routers.${CICD_STACK_NAME}App.entrypoints=websecure'
        - 'traefik.http.routers.${CICD_STACK_NAME}App.tls.certresolver=letsencrypt'
