########
# BUILD
########
.filterFastCI:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    - if: $CICD_FAST
      when: never

    # auto run
    - when: on_success

.filterBuild:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    # auto run
    - when: on_success

##########
# PUBLISH
##########
.filterPublish:
  rules:

    # not for tags
    - if: $CI_COMMIT_TAG
      when: never

    # only on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success