networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true

  central_warehouse:
    name:central_warehouse

services:
  app:
    image: $CICD_IMAGE_ID
    environment:
      - RMQ_HOST=bus
    networks:
      - bus
      # - ingress
    deploy:
      replicas: 1
      # labels:
      #   - 'traefik.enable=true'
      #   - "traefik.http.routers.${CICD_STACK_NAME}App.rule=Host(`${CI_PROJECT_NAME}.${TLD}`)"
      #   - "traefik.http.services.${CICD_STACK_NAME}App.loadbalancer.server.port=8080"
      #   - 'traefik.http.routers.${CICD_STACK_NAME}App.entrypoints=websecure'
      #   - 'traefik.http.routers.${CICD_STACK_NAME}App.tls.certresolver=letsencrypt'

  db:
    image: mysql:latest
    restart: always
    networks:
      - central_warehouse
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql
      - ./config/mysql/central_warehouse.sql:/docker-entrypoint-initdb.d/central_warehouse.sql
