version: '3.5'

networks:
  central_warehouse:
    name: central_warehouse


services:
  db1:
    image: mysql:latest
    restart: always
    networks:
      - central_warehouse
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql
      - ./config/mysql/central_warehouse.sql:/docker-entrypoint-initdb.d/central_warehouse.sql

  central_warehouse:
    image: swda-24hs/central-warehouse-service:latest
    restart: always
    networks:
      - central_warehouse

    environment:
      DATABASEUSER: swda
      DATABASEPASSWORD: swda
      DATABASEHOST: db1
      DATABASEPORT: 3306
      DATABASENAME: central_warehouse
      RMQ_HOST: host.docker.internal