include:
  - /sys/config/environments/sys.common.yml

.envConfigSysDev:
  extends: .envConfigSysCommon
  variables:

    # vault
    CICD_VT_DEFAULT_ROLE: sys.service.cicd.dev

    # registry
    CICD_VT_PULL_REGISTRIES: 'secret/sys/cicd/docker-registries/hslu-shared-devops secret/sys/cicd/docker-registries/hslu-system'

    # helm
    CICD_ENV_NAME: dev

    # kadmission: using PROD, there is no DEV (costs)
    CICD_KA_VT_DIR: secret/sys/apps/kadmission/clients/sys.prod
    CICD_KA_VT_ROLE_BASE: sys.app.kadmission.sys.prod.app

    # deploy config - dev
    CICD_VT_HOST: secret/rnd/cicd/dev/switch-k8-dev
    CICD_VT_HOST_K8_KEY: config
    CICD_INGRESS: nginx

    # hosting config - dev
    CICD_DOMAIN_INTERN: intern.dev.hslu-rnd.ch
    CICD_DOMAIN_PUBLIC: dev.dev.hslu-rnd.ch