include:
  - /sys/config/environments/sys.common.yml

.envConfigSysProd:
  extends: .envConfigSysCommon
  variables:

    # vault
    CICD_VT_DEFAULT_ROLE: sys.service.cicd.prod

    # registry
    CICD_VT_PULL_REGISTRIES: 'secret/sys/cicd/docker-registries/hslu-shared-devops secret/sys/cicd/docker-registries/hslu-system'

    # helm
    CICD_ENV_NAME: prod

    # kadmission
    CICD_KA_VT_DIR: secret/sys/apps/kadmission/clients/sys.prod
    CICD_KA_VT_ROLE_BASE: sys.app.kadmission.sys.prod.app

    # deploy config - prod  (using RnD Sys env)
    CICD_VT_HOST: secret/rnd/cicd/sys/switch-k8s-sys
    CICD_VT_HOST_K8_KEY: config
    CICD_INGRESS: nginx

    # hosting config - sys
    CICD_DOMAIN_INTERN: intern.sys.hslu-rnd.ch
    CICD_DOMAIN_PUBLIC: sys.hslu-rnd.ch
